/**
 * PDF Report Generator for Cyber Knights
 * Generates downloadable security analysis reports
 */

function generateReportText(report) {
    const lines = [];
    const div = '='.repeat(60);
    const thin = '-'.repeat(60);

    lines.push(div);
    lines.push('       CYBER KNIGHTS - SECURITY ANALYSIS REPORT');
    lines.push(div);
    lines.push('');
    lines.push(`Report ID   : ${report.report_id || 'N/A'}`);
    lines.push(`Date        : ${new Date(report.created_at || Date.now()).toLocaleString()}`);
    lines.push(`Scan Type   : ${(report.scan_type || 'APK').toUpperCase()}`);
    lines.push(`File Name   : ${report.file_name || 'N/A'}`);
    lines.push(`File Size   : ${report.file_size_kb || 0} KB`);
    lines.push(`SHA-256     : ${report.file_hash || 'N/A'}`);
    lines.push('');
    lines.push(thin);
    lines.push('RISK ASSESSMENT');
    lines.push(thin);
    lines.push(`Risk Score        : ${report.risk_score}/100`);
    lines.push(`Classification    : ${report.classification}`);
    lines.push(`Malware Detected  : ${report.malware_match ? `YES - ${report.malware_name || 'Unknown'}` : 'NO'}`);
    lines.push('');
    lines.push('Risk Formula: R = (P×5) + (M×40) + (U×10) + (A×8)');
    lines.push(`  P (Dangerous Permissions) = ${report.permission_count}`);
    lines.push(`  M (Malware Match)         = ${report.malware_match ? 1 : 0}`);
    lines.push(`  U (Suspicious URLs)       = ${report.url_count}`);
    lines.push(`  A (Suspicious APIs)       = ${report.api_count}`);
    lines.push('');
    lines.push(thin);
    lines.push('DANGEROUS PERMISSIONS DETECTED');
    lines.push(thin);

    const permissions = Array.isArray(report.permissions) ? report.permissions : [];
    if (permissions.length > 0) {
        permissions.forEach(p => lines.push(`  • ${p}`));
    } else {
        lines.push('  None detected');
    }

    lines.push('');
    lines.push(thin);
    lines.push('EMBEDDED URLS');
    lines.push(thin);
    const urls = Array.isArray(report.urls) ? report.urls : [];
    if (urls.length > 0) {
        urls.slice(0, 20).forEach(u => lines.push(`  • ${u}`));
    } else {
        lines.push('  None detected');
    }

    lines.push('');
    lines.push(thin);
    lines.push('SUSPICIOUS API CALLS');
    lines.push(thin);
    const apis = Array.isArray(report.suspicious_apis) ? report.suspicious_apis : [];
    if (apis.length > 0) {
        apis.forEach(a => lines.push(`  • ${a}`));
    } else {
        lines.push('  None detected');
    }

    lines.push('');
    lines.push(thin);
    lines.push('RECOMMENDATION');
    lines.push(thin);
    if (report.classification === 'High Risk') {
        lines.push('  ⚠ DO NOT INSTALL - This APK exhibits high-risk characteristics.');
        lines.push('  The application may be malicious. Avoid installation.');
    } else if (report.classification === 'Medium Risk') {
        lines.push('  ⚡ CAUTION - Medium risk level detected.');
        lines.push('  Review permissions carefully before installing.');
    } else {
        lines.push('  ✓ LOW RISK - No significant threats detected.');
        lines.push('  Standard security precautions recommended.');
    }

    lines.push('');
    lines.push(div);
    lines.push('  Generated by Cyber Knights Platform | cyberknights.io');
    lines.push(div);

    return lines.join('\n');
}

module.exports = { generateReportText };
